### ISSUE TITLE
Weird output for G3

### ISSUE THREAD

**Issue by dmitrykouznetsov** [chakravala/Grassmann.jl#104]
I get an odd result for a simple calculation in G3. I'm using julia 1.9.2

```
julia> basis"3"
(⟨×××⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> v1 ^ v2
-0.49259671556261386 + 0.870257706554171v₁₂
```

**Comment by chakravala** [comment]
This result is not reproducible by me on Julia 1.9.3, works fine for me

**Comment by dmitrykouznetsov** [comment]
Removing .julia folder and reinstalling somehow helped. Thanks for checking :)
