### ISSUE TITLE
Support arbitrary metrics

### ISSUE THREAD

**Issue by MasonProtter** [chakravala/Grassmann.jl#107]
It might be nice to support general, non-diagonal metrics at some point.

**Comment by chakravala** [comment]
Support for arbitrary metrics is also going to require the `VectorSpace` definitions to be updated in

DirectSum.jl : https://github.com/chakravala/DirectSum.jl

Have you familiarized yourself with that package yet?

**Comment by chakravala** [comment]
This issue will be addressed in either v0.3 or v0.4 of *DirectSum.jl* (after the extension I am currently designing for tensor fields). For me, it doesn't make sense to address this issue until the tensor fields are fully implemented.

The license of the repository is non-negotiable; however, it may be possible to separately negotiate individual licenses for specific users. This repository is the result of my own personal blood, sweat, and tears. If you want to modify and redistribute my software, GPL must be used or a very big price must be paid.

**Comment by chakravala** [comment]
Some of my repositories have the MIT license, but not this repository. MIT license would be negative for this project and also disrespectful to my expended effort on the whole foundation. For this kind of software, I would have either chosen closed source or GPL, but not MIT license. This is a special and unique effort, and making it closed source would not have benefited the project, so GPL it is.

Sprechen sie Deutsch? I am also german

What language did you use for your software?

**Comment by chakravala** [comment]
non-diagonal metric has been marked as `pay-donate` because I don't currently intend to implement it unless I am paid to work on it, since I am otherwise pre-occupied @rleegates @MasonProtter

**Comment by chakravala** [comment]
Arbitrary `MetricTensor` support has been added as of `v0.8.19` resolving this issue @MasonProtter @davibarreira
```Julia
using Grassmann
@basis MetricTensor([0 -1 0; -1 0 0; 0 0 1])
```
