### ISSUE TITLE
reverse of S/MBlade incorrect

### ISSUE THREAD

**Issue by Orbots** [chakravala/Grassmann.jl#11]
works on a Multivector and Basis, but doesn't seem to give correct result for Blades.

```
julia> a
1.0v₁ + 2.0v₂ + 0.0v₃

julia> b
3.0v₁

julia> ab = a*b
3.0 - 6.0v₁₂

julia> reverse(ab)
3.0 + 6.0v₁₂

julia> reverse(ab(2))
6.0v₁ + 0.0v₂ + 0.0v₃

julia> typeof(ab(2))
SBlade{Float64,⟨+++⟩,2,3}

**Comment by MasonProtter** [comment]
I have a fork with all the `@pure` annotations removed and your example works in that fork: https://github.com/MasonProtter/Grassmann.jl

```julia
julia> using Grassmann

julia> basis"+++"
(⟨+++⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> a = 1.0v1 + 2.0v2 + 0.0v3
1.0v₁ + 2.0v₂ + 0.0v₃

julia> b = 3.0v1
3.0v₁

julia> ab = a*b
3.0 - 6.0v₁₂

julia> reverse(ab)
3.0 + 6.0v₁₂

julia> ab(2)
-6.0v₁₂ + 0.0v₁₃ + 0.0v₂₃

julia> reverse(ab(2))
6.0v₁ + 0.0v₂ + 0.0v₃
```
This indicates that this error is due to https://github.com/chakravala/Grassmann.jl/issues/9

**Comment by chakravala** [comment]
@Orbots  actually mistaken, this may not be a bug at all

I ran the same code that @MasonProtter ran on my branch, and I got the same exact output
```Julia
julia> using Grassmann

julia> basis"+++"
(⟨+++⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> a = 1.0v1 + 2.0v2 + 0.0v3
1.0v₁ + 2.0v₂ + 0.0v₃

julia> b = 3.0v1
3.0v₁

julia> ab = a*b
3.0 - 6.0v₁₂

julia> reverse(ab)
3.0 + 6.0v₁₂

julia> ab(2)
-6.0v₁₂ + 0.0v₁₃ + 0.0v₂₃

julia> reverse(ab(2))
6.0v₁ + 0.0v₂ + 0.0v₃
```
Can you start a clean session or go back in your history and check how you defined `a` and `b`?

**Comment by MasonProtter** [comment]
@chakravala Yes, apologies I deleted my comment after realizing I misinterpreted the bug, ie. it's not fixed by removing `@pure`. I do think it is a bug though, correct? Reverse `-6.0v12` should be `6.0v12`, not `6.0v1`

**Comment by MasonProtter** [comment]
Minimal working example:
```julia
julia> reverse(-6.0v12)
6.0v₁₂

julia> reverse(-6.0v12 + 0.0v13)
6.0v₁ + 0.0v₂ + 0.0v₃
```

**Comment by Orbots** [comment]
Correct.  This should pass:  `@test reverse(v12 + 0.0v13) == v2*v1 + 0.0v13 == -v12 0.0v13`

Edit: corrected test.

**Comment by chakravala** [comment]
This is now fixed in the commit I just pushed, the grade should have been `G` instead of `N-G`.

I will add the test on a future commit or you can make a pull request with more tests

**Comment by Orbots** [comment]
Thanks for the quick response!

**Comment by chakravala** [comment]
That bug would have taken me longer to find on my own!

By the way, I just had to force push the commit once more, now I understand where mistake came from, it was because I had re-used a similar code from the complement, but didn't change the grade.
