### ISSUE TITLE
Definition of inner product

### ISSUE THREAD

**Issue by karlwessel** [chakravala/Grassmann.jl#21]
Which definition of the inner product between multivectors do you use? I'm asking because I was confused by the fact that `v1 ⋅ v12` is giving me `0` as a result, and I would have expected some multiple of v1 (which `v12 ⋅ v1` gives me).

**Comment by chakravala** [comment]
In `Grassmann` the contraction product is defined as the *right* contraction, not the *left* contraction. The reason for my selection of this convention will be explained in my paper published in a few weeks.

**Comment by karlwessel** [comment]
Ok, I was almost guessing that it was the right contraction, thanks for the quick confirmation.

**Comment by chakravala** [comment]
In many papers and literature, the left contraction convention is used.. but I view this as incorrect, as I will explain in my paper. Some formulas and equations are actually simpler with the right contraction.

This also happens to be the same way that Hermann Grassmann originally defined it himself.

Some other researchers have become accustomed to the left contractions... however.
