### ISSUE TITLE
left contraction definition

### ISSUE THREAD

**Issue by Orbots** [chakravala/Grassmann.jl#27]
julia> basis"+++"
(⟨+++⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> v1⨼(v1*v2)
-1v₂

julia> v1*(v1*v2)
v₂

**Comment by chakravala** [comment]
This is correct according to the definition that is used
```Julia
julia> basis"+++"
(⟨+++⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> ⋆(v1)∨(v12)
-1v₂

julia> v1*v12
v₂
```
The definition is `⨼(a,b) = ⋆(a) ∨ b` with the `complementright` Hodge complement.

Are you expecting something different?

**Comment by chakravala** [comment]
Perhaps it would be better if the definition is changed to this:
```Julia
⨼(a,b) = b ∨ ⋆(a)
```
with the order of the product reversed? then you get a sign that maybe fits into the standard notions?

it seems that the product would probably have to be reversed in the definition, what do you think?

in that case, we could simply define it as ` ⨼(a,b) = b ⨽ a` and it could inherit the optimizations of `⨽`

**Comment by Orbots** [comment]
I'm using the definitions of contractions as selecting a specific grade from the geometric product of two multivectors.   (2.6) and (2.7) from https://www.researchgate.net/publication/2842332_The_Inner_Products_of_Geometric_Algebra
Which in that paper is actually a result of interaction of the geometric scalar product and the wedge operator.

I have to admit I don't really know what the hodge star is for G3, it's from exterior algebra, right?  I know what it does and how it's related to the dual operator in G3, but AFAIK it may be off by a sign flip.  So I can't really comment on any definition involving the hodge star.   Seems that the relation from the paper I linked should hold though.
