### ISSUE TITLE
Please add a simpler introduction to the README for beginners, thanks.

### ISSUE THREAD

**Issue by robwebbjr** [chakravala/Grassmann.jl#32]
Hi.
Thanks for helping to push geometric algebra into the mainstream with your hard work.
I am reading introductory material on GA and using Clifford (Python) to add, multiply, reflect, etc.
For the most part, I bypassed linear algebra and just took up with GA because it looks interesting. 
I would like to use Julia (and Grassmann) to learn GA, but I don't understand most of the README, yet.
In particular, I couldn't tell how to simply add, multiply or reflect a vector in R3.
I was able to use Clifford because I could follow their docs, but the Grassmann README seems geared to people who already know what they are doing... 
Thanks, again.

**Comment by chakravala** [comment]
Alright, I will be updating the README with better information after I finish up the JuliaCon paper.

You are also welcome to contribute to the documentation or README with your own ideas.

**Comment by robwebbjr** [comment]
Excellent!
Thanks a lot!
I do appreciate the immense effort not just to create something like Grassmann, but to learn all of the required knowledge in the first place.
As I become more knowledgeable, I will give back as best I can.
Thanks again!

**Comment by chakravala** [comment]
Also, while I believe that abstract algebra and geometric algebra can go before matrix representations,  I recommend you also study some linear algebra and multi-linear algebra also.

**Comment by robwebbjr** [comment]
Thank you.
I do have a rudimentary understanding of (single) linear algebra and simple matrix arithmetic, and I anticipate gaining a fuller knowledge of LA in the course of pursuing geometric algebra (and yes, abstract algebra also). 
Believe it or not, despite my admittedly lazy approach to mathematics, my ultimate goal is to make use of (as in apply to physics and engineering) geometric algebra and homotopy type theory in an effort to quantify a lifetime's worth of metaphysical experience, and derive some usably concrete application(s).
In light of said personal experience, reading works like "The Shape of Inner Space", "The Hidden Reality", "Nexus Graviton", and "The Mystical Qabalah" inclines me to believe that a model of physical reality as an emergent phenomenon of what I call the "Abstract Information Field" (aka 'Consciousness' or 'Mind') would eventually contribute much to human technological advancement. 
For example, while reading Jaap Suter's "Geometric Algebra Primer", it occurred to me that the orientation (read spin) inherent in a multi-vector perfectly reflects both the metaphysical tradition that material creation has its genesis (and foundation) in a spinning/spiraling/rotation of abstract potential, as well as the observation that, barring tidal lock, or some other reason, every body in the cosmos appears to rotate about an inner axis...
So here I am, learning to use the tools that you are crafting.
By the way, I did figure out how to do simple multi-vector operations with Grassmann from reading the README; I just needed to slow down and read more closely, so thank you for that!
Nevertheless, I am pretty sure that eventually, some brilliant six year old will greatly appreciate your patient explanation of the basics of how to use Grassmann on her journey to formulating the next Great Theory...
Thanks again and Be Well.

**Comment by goballooning** [comment]
Maybe also add some recommendations on abstract algebra/vector bundle/tangle space, so that an application orientated user knows the Grassmann API better.
(random thoughts: add references around API / some documentation of API directly?)

Cheers.

**Comment by chakravala** [comment]
There has been some more progress with documentation at https://grassmann.crucialflow.com/dev

**Comment by robwebbjr** [comment]
Excellent; thank you for all of your hard work!
I'm actually in the middle of linear algebra and differential equations,
afterwards I plan to work through Snygg's "A New Approach to Differential
Geometry Using Clifford's Geometric Algebra"; concurrently, I hope be able
to start learning to use Grassmann profitably.
Thanks again.
