### ISSUE TITLE
wedge product of scalars, reversion, and conjugate

### ISSUE THREAD

**Issue by Orbots** [chakravala/Grassmann.jl#5]
In geometric algebra at least the 0-vector wedged with another 0-vector should be non-zero if both scalars are non-zero.

`julia> 2v∧3v`
`0v`

**Comment by chakravala** [comment]
Thanks for opening the issue. Yes, I was already aware the scalars are not behaving correctly, I was thinking about how to resolve that issue on my next update. Please report any other issues you find.

The scalars are a special case, and need to have extra decision logic to handle correctly.

**Comment by Orbots** [comment]
Thanks.  I have a few other things.  I'm working on some discrete differential geometry applications and thought it would be interesting to use some form of GA.  

I haven't looked into the implementation here, but the simplest way to handle a scalar would be to let methods operating on scalars "fall though" to just plain old scalar types, no?  I can see how the implementation of that could get quite tricky.

The main thing I'd like to do now that I can't see in this package yet is the ability to get the reversion of a Multivector.  http://geocalc.clas.asu.edu/pdf/NFMPchapt1.pdf  ( search for reversion ).  Maybe this is possible already ( seems like a fairly easy thing to implement )?  Ultimately the inverse of a Blade is what I really want.  Reversion can give you the inverse easily for a common class of Blades though.

**Comment by chakravala** [comment]
Alright, well I am also intending to use GA for differential geometry related research work. If you decide to use Grassmann.jl to do some calculations, please make your work open-source, it will help accelerate the devleopment of this package by finding issues and making more things possible.

The commutativity of the scalars should now be resolved with commit e1f29fed272e1deb259725ff4cc000c8ee868e7b, which is going to be part of the v0.0.3 release very soon, that was a very simple matter to fix.

Thanks for sharing the link regarding the reversion operation. Yes, it should be possible to implement. So it is an operation mainly only involving a change in parity for each grade? I am still somewhat new to the whole field of geometric algebra, but intend to have all these operations available in `Grassmann`.

In the next commit, I intend to have the `reverse`, `involve`, and `conj` methods all available.

**Comment by chakravala** [comment]
@Orbots the `reverse`, `involve` and `conj` methods have now been implemented on `master`, along with the other previous methods like `complementleft`, `complementright`, and `adjoint`.

As you can see in the commit 8c635cfa498f676a6ecf4e75020cda6aa3ebb077, few extra definitions were required to include these operations.

Could you please clarify if these operations are completely independent of the metric signature?

This will be tagged as part of v0.0.3 this weekend.

The more feedback you provide, the more you help potentially accelerate development.

**Comment by chakravala** [comment]
Since everything that has been discussed in this issue has now been addressed in the [v0.0.3](https://github.com/chakravala/Grassmann.jl/releases/tag/v0.0.3) release, this issue is now being closed. It is recommended you provide some more feedback with your experiences now that the `reverse` operations are available.

These are the definitions I used for the parity of the operations
```Julia
parityreverse(G) = isodd(Int((G-1)*G/2))
parityinvolve(G) = isodd(G)
parityconj(G) = parityreverse(G)⊻parityinvolve(G)
```
Do you happen to know if they only depend on the grade `G` or if the metric is also involved?

Note that if you need to define additional operations derived as a composition of these and the other existing operations, then you can get a performance boost by creating a new product call method. This is how for example the inner product is defined: instead of doing the actual composition, it is skipped into.

**Comment by Orbots** [comment]
@chakravala thanks for this.  Scalars as 0-vectors are handled correctly now.

I'm lucky enough to be paid to do this.  We do have a policy for open sourcing our code and I do intend to open source what I can.  There is a process involved though.

I'm pretty new to this too and not a mathematician!  Appologies if my terminology is not precise.

Not entirely sure about what the metric signature means.  I'm also learning differential forms at the same time.  I think are you talking about the effect of reversion on covectors and the inner product?  Not sure that reversion makes sense in "classic" differential geometry.  Geometric Algebra has an inverse operator, whereas differential geometry does not.  For me reversion is a transform I'll use to define the inverse operator.  `B*B^1 = I`  I'd say it has no effect on the metric, but also doesn't make too much sense operating on a covector .

reverse will reorder the 1-vectors composing the blade.  If the blade is a k-vector the reversed blade should also be a k-vector.  reverse should simply end up as potentially a sign flip as you are keeping the k-vectors organized in ascending order.   i.e. `v2*v1 = -1v₁₂` and not `v2*v1 = 1v₂₁`.   We reverse the order from ascending to descending, then flip signs as we go back to ascending order.  So we just need to count the number of sign flips, which for an n-vector/blade should be  `reverse(B) = B*(-1)^(n*(n-1)/2)`

Sorry, I haven't taken the time to really learn how your code works.  I'll endeavour to do so!

Cheers.

**Comment by EricLengyel** [comment]
I've posted some recent conclusions I've made about the wedge product of scalars that you might find interesting:

http://terathon.com/blog/wedge-and-dot-products-involving-scalars/

**Comment by chakravala** [comment]
Thanks for linking, also the comments in this particular issue are probably now out of date by the way.
