### ISSUE TITLE
\oslash documentation is wrong

### ISSUE THREAD

**Issue by eschnett** [chakravala/Grassmann.jl#55]
The documentation for \oslash reads:
```
Sandwich product: ω⊘η = (~ω)⊖η⊖ω
```

However, it seems to implement `η⊘ω` instead (with arguments commuted):

```Julia
julia> R = exp(π/4*v12)
0.7071067811865476 + 0.7071067811865475v₁₂

julia> (~R) ⊖ v1 ⊖ R
0.0 + 2.220446049250313e-16v₁ + 1.0v₂

julia> R ⊘ v1
-0.7071067811865476 + 0.7071067811865475v₁₂

julia> v1 ⊘ R
0.0 + 2.220446049250313e-16v₁ + 1.0v₂
```

**Comment by chakravala** [comment]
Note that ⊘ is a new symbol definition which has not quite existed before I defined it. Most literature uses the `>>>` definition instead, which I think is slightly wrong as a definition.
