### ISSUE TITLE
Documentation for \oslash is incomplete

### ISSUE THREAD

**Issue by eschnett** [chakravala/Grassmann.jl#57]
According to the documentation of `\oslash`, this should hold:
```Julia
help?> ⊘
"⊘" can be typed by \oslash<tab>

search: ⊘

  ⊘(ω::TensorAlgebra,η::TensorAlgebra)

  Sandwich product: ω⊘η = (~η)⊖ω⊖η

julia> v⊘v1 == (~v1)⊖v⊖v1
false
```

**Comment by chakravala** [comment]
The documentation is not exactly wrong, it's just incomplete:
```
General sandwich product: ω⊘η = involute(η)\ω⊖η
For normalized even grade η it is ω⊘η = (~η)⊖ω⊖η
```
Indeed, the exact definition is `ω⊘η = involute(η)\ω⊖η` and the definition currently in the doc string is only valid for a limited range of input. This is becuase my definition is more generalized than the traditional definition used by everybody else.

Your example is a reflection, and in the traditional literature the sandwich formula is not defined in such a way as to do reflections correctly. This is why `(~η)⊖ω⊖η` is incorrect as a definition in the most general use cases. However, the definition is used often in the literature, and is more familiar to people who read the geometric algebra literature. Hence, I used it in the doc string.

My own definition of `\oslash` is more general, and also takes reflections (like your example) into account. The definition in the doc string is insufficient for that, so I extended the explanation.

This is why my new definition is in fact better than the one in the traditional literature. Now I have updated the docstring to expand on this detial more, which I didn't explain before.

Your example illustrates where the shortcoming of the traditional definition is, which is only valid for rotations but not valid for reflections. My formula is more general, so the docs should mention that.
