### ISSUE TITLE
Type instability in abs2 for Chain

### ISSUE THREAD

**Issue by eschnett** [chakravala/Grassmann.jl#63]
Applying `abs2` to a `Chain` loses type information

```Julia
julia> S = S"∞∅++"
⟨∞∅++⟩
julia> V = SubManifold(S)
⟨∞∅++⟩
julia> B = Λ(S)
DirectSum.Basis{⟨∞∅++⟩,16}(v, v∞, v∅, v₁, v₂, v∞∅, v∞₁, v∞₂, v∅₁, v∅₂, v₁₂, v∞∅₁, v∞∅₂, v∞₁₂, v∅₁₂, v∞∅₁₂)
julia> x = Chain(B.v1)
0v∞ + 0v∅ + 1v₁ + 0v₂
julia> x |> typeof
Chain{⟨∞∅++⟩,1,Int64,4}
julia> abs2(x) |> typeof
MultiVector{⟨∞∅++⟩,Any,16}
```

While `x` has element type `Int`, `abs2(x)` has only `Any`.

**Comment by eschnett** [comment]
A similar issue arises for `<`. `x` is defined the same as above:
```Julia
julia> x < x
1v⃖

julia> typeof(x < x)
MultiVector{⟨∞∅+⟩,Any,8}

julia> dump(x < x)
MultiVector{⟨∞∅+⟩,Any,8}
  v: SArray{Tuple{8},Any,1,8}
    data: Tuple{Rational{Int64},Float64,Float64,Float64,Float64,Float64,Float64,Float64}
      1: Rational{Int64}
        num: Int64 1
        den: Int64 1
      2: Float64 0.0
      3: Float64 0.0
      4: Float64 0.0
      5: Float64 0.0
      6: Float64 0.0
      7: Float64 0.0
      8: Float64 0.0
```

It seems that the type `Float64` is introduced somewhere. Julia likes this type; if one starts from `Int` and uses division, the result is `Float64`. To remove the type instability, one typically has to use `one(T)` or `zero(T)`.

I think that Grassmann automatically converts `v1` to `1v1`, which could explain the problem above.

**Comment by chakravala** [comment]
This bug has been fixed in the most recent commit https://github.com/chakravala/Grassmann.jl/commit/b324d1c00c9bc6e7896d77c48950ec588f74c943
