### ISSUE TITLE
Makie plot examples in README

### ISSUE THREAD

**Issue by lukeburns** [chakravala/Grassmann.jl#70]
May be helpful to add `AbstractPlotting.inline!(true)` to Makie plot examples for newcomers so they're not confused (like I was!). https://github.com/JuliaPlots/Makie.jl/issues/392

**Comment by RalfBarkow** [comment]
@lukeburns This needs to be false to show a plot in a window when in the REPL.

**Comment by chakravala** [comment]
I'll go with what @RalfBarkow said, and close the issue then
