### ISSUE TITLE
Undef var error in call to submanifold

### ISSUE THREAD

**Issue by maxfreu** [chakravala/Grassmann.jl#75]
Hi, in forms.jl, line 88 there is a call to `return b`, but it seems to be undefined.

```julia
function (W::SubManifold{Q,M,S})(m::MultiVector{V,T}) where {Q,M,V,S,T}
    if isbasis(W)
        throw(error("MultiVector forms not yet supported"))
    elseif V==W
        return b
...
```
Grassmann version 0.5.21

**Comment by chakravala** [comment]
Thank you, the bug has been fixed in `v0.6.1` (which is on the latest commit but not yet released)
