### ISSUE TITLE
A problem on interoperability with AbstractTensors

### ISSUE THREAD

**Issue by hammerfunctor** [chakravala/Grassmann.jl#80]
When I try to construct a tensor, the output is like below
```julia
julia> using Grassmann, AbstractTensors; basis"+---"
(⟨+---⟩, v, v₁, v₂, v₃, v₄, v₁₂, v₁₃, v₁₄, v₂₃, v₂₄, v₃₄, v₁₂₃, v₁₂₄, v₁₃₄, v₂₃₄, v₁₂₃₄)

julia> Values(v1*v1, v1*v2)
2-element Values{2,Simplex{⟨+---⟩,0,v,Number}} with indices SOneTo(2):
 1v
 1v
```
while the expected output is like
```julia
1v
v12
```
Since I'm a novice to both differential geometry and `Grassmann.jl`, I have no idea whether it's a bug or some property of differential geometry.

**Comment by hammerfunctor** [comment]
I use `Grassmann.jl v0.7.1` on macOS.

**Comment by chakravala** [comment]
it is likely due to a type promotion gone wrong somewhere

I will investigate it when I get around to updating the next version of `AbstractTensors`

you can optionally depend on `StaticArrays` instead by precompiling `AbstractTensors` with environment variable `STATICJL`.

**Comment by hammerfunctor** [comment]
I find another way to bypass this problem.
```julia
Values(v, v1*v2)
```
This line will give the true output.

**Comment by chakravala** [comment]
This bug appears to be fixed for me now, so I'm going to close this issue.
