### ISSUE TITLE
grade selection attempt: ERROR: MethodError: no method matching (::Simplex{⟨+++⟩,1,v₂,Int64})(::Int64)

### ISSUE THREAD

**Issue by peeterjoot** [chakravala/Grassmann.jl#84]
Setup basis with:

    using Grassmann; @basis S"+++"

(R^3)

and can successfully select grades from some geometric products:

    julia> ((v12 + v23) * v2)(0)
    0v

    julia> ((v12 + v23) * v2)(1)
    1v₁ + 0v₂ - 1v₃

but not others:

julia> (v12 * v1)(1)
ERROR: MethodError: no method matching (::Simplex{⟨+++⟩,1,v₂,Int64})(::Int64)
Closest candidates are:
  Any(::SubManifold{V,1,Indices} where Indices) where V at /home/pjoot/.julia/packages/DirectSum/aSUXQ/src/operations.jl:247
  Any(::Simplex{V,1,B,T} where T where B) where V at /home/pjoot/.julia/packages/DirectSum/aSUXQ/src/operations.jl:252
  Any(::Chain{V,1,𝕂,253} where 253 where 𝕂) where V at /home/pjoot/.julia/packages/Grassmann/Tvf1n  /src/forms.jl:253
  ...
Stacktrace:
 [1] top-level scope at REPL[9]:1    

Software:

# julia --version
julia version 1.4.1

(default for Ubuntu 20.04.1)

**Comment by peeterjoot** [comment]
Note.  using a temporary variable doesn't help:

julia> using Grassmann; @basis S"+++"
(⟨+++⟩, v, v₁, v₂, v₃, v₁₂, v₁₃, v₂₃, v₁₂₃)

julia> a = v12 * v1
-1v₂

julia> a(1)
ERROR: MethodError: no method matching (::Simplex{⟨+++⟩,1,v₂,Int64})(::Int64)
Closest candidates are:
  Any(::SubManifold{V,1,Indices} where Indices) where V at /home/pjoot/.julia/packages/DirectSum/aSUXQ/src/operations.jl:247
  Any(::Simplex{V,1,B,T} where T where B) where V at /home/pjoot/.julia/packages/DirectSum/aSUXQ/src/operations.jl:252
  Any(::Chain{V,1,𝕂,253} where 253 where 𝕂) where V at /home/pjoot/.julia/packages/Grassmann/Tvf1n/src/forms.jl:253
  ...
Stacktrace:
 [1] top-level scope at REPL[3]:1

julia> a(0)
ERROR: MethodError: no method matching (::Simplex{⟨+++⟩,1,v₂,Int64})(::Int64)
Closest candidates are:
  Any(::SubManifold{V,1,Indices} where Indices) where V at /home/pjoot/.julia/packages/DirectSum/aSUXQ/src/operations.jl:247
  Any(::Simplex{V,1,B,T} where T where B) where V at /home/pjoot/.julia/packages/DirectSum/aSUXQ/src/operations.jl:252
  Any(::Chain{V,1,𝕂,253} where 253 where 𝕂) where V at /home/pjoot/.julia/packages/Grassmann/Tvf1n/src/forms.jl:253
  ...
Stacktrace:
 [1] top-level scope at REPL[4]:1

**Comment by chakravala** [comment]
You can now get around this issue in Grassmann `v0.8` by using `grade(t, g)` or `grade(t, ::Val{g})` where `g` is selected `grade`,

**Comment by peeterjoot** [comment]
Okay, thanks.  I'll give it a new try.

**Comment by peeterjoot** [comment]
Works nicely.

**Comment by chakravala** [comment]
You may also want to look at the documentation for `Val` as well
https://docs.julialang.org/en/v1/base/base/#Base.Val
