### ISSUE TITLE
Incorrect geometric square `(v12 + v34)^2`.

### ISSUE THREAD

**Issue by Jollywatt** [chakravala/Grassmann.jl#89]
I don't believe this behaviour is intentional:
```julia
julia> @basis 4 # or any space of dimension at least four
(⟨××××⟩, v, v₁, v₂, v₃, v₄, v₁₂, v₁₃, v₁₄, v₂₃, v₂₄, v₃₄, v₁₂₃, v₁₂₄, v₁₃₄, v₂₃₄, v₁₂₃₄)

julia> a = v12 + v34
1v₁₂ + 0v₁₃ + 0v₁₄ + 0v₂₃ + 0v₂₄ + 1v₃₄

julia> a*a
-2 + 2v₁₂₃₄

julia> a^2
-2v
```

In general, if `a` is a `k`-vector, then `a^2` may have non-zero projections of grade `0, 4, 8, ...`. (Proof: `a^2` is its own `reverse` so has grade `{4n, 4n + 1 | n ∈ ℕ}` , and its own `involute` so has even grade.)

**Comment by chakravala** [comment]
You seem to be using an outdated version of `Grassmann` you need to update to the latest version.
```Julia
julia> a = (v12+v34)
1v₁₂ + 0v₁₃ + 0v₁₄ + 0v₂₃ + 0v₂₄ + 1v₃₄

julia> a*a
-2 + 2v₁₂₃₄

julia> a^2
-2 + 2v₁₂₃₄
```
This was issue was already raised and fixed: https://github.com/chakravala/Grassmann.jl/issues/86
