### ISSUE TITLE
Unknown symbol in 5D CGA Basis

### ISSUE THREAD

**Issue by mw95710** [chakravala/Grassmann.jl#97]
I tried generating the 5D CGA basis:

@basis S"∞∅+++"

Let x be a point: x = v1 + v2 + v3. When I calculate x^2, I get 3v\overleftarrow. My question is what does the v\overleftarrow symbol represent? This is not an issue if I use the normal 3D GA (@basis S"+++") and I get the expected x^2 = 3v. v\overleftarrow performs the same as v, but I was wondering if the \overleftarrow mean anything.

Thank you

**Comment by chakravala** [comment]
The point of v\overleftarrow is to visually confirm that the element is a **full** Multivector despite only being scalar in value. A scalar allocated to a Full Multivector is of course less desirable than a sparse scalar element.
